[0m09:37:17.005161 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F9BF3BFA10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F9BE340910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F9C15CBED0>]}


============================== 09:37:17.079125 | 411745e6-417d-4cc6-b558-3fd0784fabdc ==============================
[0m09:37:17.079125 [info ] [MainThread]: Running with dbt=1.9.4
[0m09:37:17.080170 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\R\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init dbt_code', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m09:37:17.420445 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/R/.dbt')}
[0m09:37:17.421530 [info ] [MainThread]: Creating dbt configuration folder at 
[0m09:37:17.436803 [debug] [MainThread]: Starter project path: D:\oop_ai\ai2-data-engineering\ai2-data-engineering-opa24\6_setup_dbt\.venv\Lib\site-packages\dbt\include\starter_project
[0m09:37:17.454806 [info ] [MainThread]: 
Your new dbt project "dbt_code" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:37:17.458365 [info ] [MainThread]: Setting up your profile.
[0m09:41:29.000885 [info ] [MainThread]: Profile dbt_code written to C:\Users\R\.dbt\profiles.yml using target's sample configuration. Once updated, you'll be able to start developing with dbt.
[0m09:41:29.002704 [debug] [MainThread]: Command `dbt init` succeeded at 09:41:29.002517 after 252.17 seconds
[0m09:41:29.003213 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F9C16CDF30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F9C167EE70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F9C1616CF0>]}
[0m09:41:29.003709 [debug] [MainThread]: Flushing usage events
[0m09:41:29.442340 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:56:05.884040 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027AAF9CF8C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027AAEA18910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027AB1C2FED0>]}


============================== 08:56:05.917987 | b1cdf982-a3f1-41e9-ae08-071a5334bc87 ==============================
[0m08:56:05.917987 [info ] [MainThread]: Running with dbt=1.9.4
[0m08:56:05.918690 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\watra\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init dbt_code', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m08:56:05.983568 [info ] [MainThread]: A project called dbt_code already exists here.
[0m08:56:05.984514 [debug] [MainThread]: Command `dbt init` succeeded at 08:56:05.984397 after 0.45 seconds
[0m08:56:05.984907 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027AB1D190F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027AB1D40EF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027AB1AF2AD0>]}
[0m08:56:05.985376 [debug] [MainThread]: Flushing usage events
[0m08:56:06.422324 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:56:52.158202 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C8DCEC7770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C8DAD61590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C8DABDF110>]}


============================== 08:56:52.162174 | 338b7143-2b34-4d05-b93a-47c6f243a46d ==============================
[0m08:56:52.162174 [info ] [MainThread]: Running with dbt=1.9.0
[0m08:56:52.162792 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\watra\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --models staging.original_headline', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m08:56:52.163225 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\education\ai_developer\ai2_data_engineering_opa24_code_along\6_setup_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:56:52.164275 [debug] [MainThread]: Command `dbt run` failed at 08:56:52.164163 after 0.31 seconds
[0m08:56:52.164685 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C8DDF48050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C8DDD3B1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C8DDE49AE0>]}
[0m08:56:52.165029 [debug] [MainThread]: Flushing usage events
[0m08:56:52.649800 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:57:09.173787 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024CE2676A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024CE06525D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024CE332D810>]}


============================== 08:57:09.192727 | 4ac7e851-f6f2-48c4-baf7-e86b8e6dd212 ==============================
[0m08:57:09.192727 [info ] [MainThread]: Running with dbt=1.9.4
[0m08:57:09.193355 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\watra\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --models staging.original_headline', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m08:57:09.193773 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\education\ai_developer\ai2_data_engineering_opa24_code_along\6_setup_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:57:09.194636 [debug] [MainThread]: Command `dbt run` failed at 08:57:09.194527 after 0.29 seconds
[0m08:57:09.194959 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024CE36CF5C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024CE36571D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024CE36338A0>]}
[0m08:57:09.195295 [debug] [MainThread]: Flushing usage events
[0m08:57:09.634421 [debug] [MainThread]: An error was encountered while trying to flush usage events
